privacy/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from django.conf.urls import include, url
from siteapp  import views

urlpatterns = [
	path('admin/', admin.site.urls),
	url(r'^$', views.home, name='home'),
	url(r'^login/$', auth_views.login, {'template_name': 'siteapp/login.html'}),
	url(r'^logout/$', auth_views.logout,{'template_name': 'siteapp/logout.html'}),
	url(r'^register/', views.register),
    url(r'^notify/', views.notification), 
	url(r'^post/', views.post), 
    url(r'^feed/', views.post), 
     url(r'^profile/', views.profile), 
]








siteapp/models.py
from django.db import models

# Create your models here.



from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib.auth.models import AbstractUser


class posts(models.Model):
	fromuser = models.CharField(max_length=50,blank=True)
	touser = models.CharField(max_length=50, blank=True)
	message= models.TextField(max_length=100,blank=True)
	permission = models.BooleanField(default=False)
	image = models.ImageField()
	location= models.TextField(max_length=100,blank=True)
	typeof = models.CharField(max_length=50, blank=True)
	testimageloc=models.CharField(max_length=50, blank=True)

class imagesmodel(models.Model):
	image = models.ImageField()
	uname=models.CharField(max_length=50,blank=True)
	created = models.DateTimeField(auto_now=True)

	def __str__(self):
		return self.uname+" "+str(self.image)

siteapp/forms.py

from django import forms

from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class ImageUploadForm(forms.Form):
    """Image upload form."""
    image = forms.ImageField()
    


class UserRegistrationForm(forms.Form):
    username = forms.CharField(
        required = True,
        label = 'Username',
        max_length = 32
    )
    email = forms.CharField(
        required = True,
        label = 'Email',
        max_length = 32,
    )
    first_name = forms.CharField(
        required = True,
        label = 'Password',
        max_length = 32,
        widget = forms.PasswordInput()
    )
    last_name= forms.CharField(
        required = True,
        label = 'First name',
        max_length = 32,
        widget = forms.PasswordInput()
    )
    password = forms.CharField(
        required = True,
        label = 'Last name',
        max_length = 32,
        widget = forms.PasswordInput()
    )
    image = forms.ImageField(required=False)

siteapp/views.py


# Create your views here.
from django.http import HttpResponse
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from django import forms
from .forms import UserRegistrationForm,ImageUploadForm

from django.core.files.storage import FileSystemStorage

import cv2, os
import numpy as np
from PIL import Image
from .models import posts,imagesmodel

def home(request):

	return render(request,'siteapp/home.html')

def profile(request):
    temp=User.objects.filter(username=request.user.username)
    userobj=temp[0]
    context={
    'userobj':userobj
    }
    return render(request,'siteapp/profile.html',context)
subjects=["","krish","bala"]
def register(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            userObj = form.cleaned_data
            username = userObj['username']
            email =  userObj['email']
            password =  userObj['password']
            first_name = userObj['first_name']
            last_name=  userObj['last_name']
            
            if not (User.objects.filter(username=username).exists() or User.objects.filter(email=email).exists()):
                User.objects.create_user( userObj['username'], first_name=userObj['first_name'],last_name=userObj['last_name'], password=userObj['password'], email=userObj['email'])
                user = authenticate(username = username, password = password)
                subjects.append(username)
                stri=str(subjects.index(username))  
                stri="C:/Users/rajgoku/Desktop/python pro/privacy/siteapp/static/s"+stri  
                if os.path.isdir(stri)==False:  
                    os.mkdir(stri)
                login(request, user)
                return HttpResponseRedirect('/feed')
            else:
                raise forms.ValidationError('Looks like a username with that email or password already exists')
    else:
        form = UserRegistrationForm()
    return render(request, 'siteapp/signup.html', {'form' : form})




cascadePath = "C:/Users/rajgoku/Desktop/python pro/privacy/siteapp/static/opencv-files/lbpcascade_frontalface.xml"
faceCascade = cv2.CascadeClassifier(cascadePath)
    
# For face recognition we will the the LBPH Face Recognizer 
recognizer = cv2.face.LBPHFaceRecognizer_create()



def get_images_and_labels(path):
    # Append all the absolute image paths in a list image_paths
    # We will not read the image with the .sad extension in the training set
    # Rather, we will use them to test our accuracy of the training
    dirs = os.listdir(path)
    print(dirs)
    images = []
    # labels will contains the label that is assigned to the image
    labels = []
    for dir_name in dirs:
        if not dir_name.startswith("s"):
            continue;
        label = int(dir_name.replace("s", ""))
        subject_dir_path = path + "/" + dir_name
        subject_images_names = os.listdir(subject_dir_path)
        for image_name in subject_images_names:
            if image_name.startswith("."):
                continue;
            image_path = subject_dir_path + "/" + image_name
            print(image_path)
            image_pil = Image.open(image_path).convert('L')

            image = np.array(image_pil, 'uint8')

        # Get the label of the image
            nbr = int(dir_name.replace("s", ""))
        # Detect the face in the image
         
            faces = faceCascade.detectMultiScale(image)
        # If face is detected, append the face to images and the label to labels
            for (x, y, w, h) in faces:
                images.append(image[y: y + h, x: x + w])
                labels.append(nbr)
            
    # return the images list and labels list
    return images, labels




def post(request):
    username = None
    username = request.user.username
    string=str(subjects.index(username))
    # feedpath="C:/Users/rajgoku/Desktop/python pro/privacy/siteapp/static/s"+string
    # image_names = os.listdir(feedpath)
    # imagelist=[]
    # for image_name in image_names:
    #         if image_name.startswith("."):
    #             continue;
    #         image_name1="s"+string+"/"+image_name
    #         imagelist.append(image_name1)
    imgobj=imagesmodel.objects.filter(uname=username).order_by('-created')
    
    context={
    'images':imgobj,
    'stringnum':string,

    }
    if request.method == 'POST' and request.FILES['myfile']:
        myfile = request.FILES['myfile']
        print(type(myfile))
        

       
        location='C:/Users/rajgoku/Desktop/python pro/privacy/siteapp/static/test'
        fs = FileSystemStorage(location=location)
        filename = fs.save(myfile.name, myfile)
        filenme=myfile.name
        uploaded_file_url = fs.url(filename)
        images, labels = get_images_and_labels("C:/Users/rajgoku/Desktop/python pro/privacy/siteapp/static")
        print("Total faces: ", len(images))
        print("Total labels: ", len(labels))
        recognizer.train(images, np.array(labels))
        temp_url="C:/Users/rajgoku/Desktop/python pro/privacy/siteapp/static/test/"+uploaded_file_url
        predict_image_pil = Image.open(temp_url).convert('L')
        predict_image = np.array(predict_image_pil, 'uint8')
        faces = faceCascade.detectMultiScale(predict_image)
        print(type(faces))
        message=None
        noface=False
        nbr_predicted=None
        predicted_name=None
        predicted_array=[]
        if type(faces) is np.ndarray:
            for (x, y, w, h) in faces:
                nbr_predicted, conf = recognizer.predict(predict_image[y: y + h, x: x + w])
                
                predicted_name=subjects[nbr_predicted]
                predicted_array.append(predicted_name)
                print(conf)
        else:
            noface=True
        print(username)
        print(predicted_name)
        print(noface)
        location='C:/Users/rajgoku/Desktop/python pro/privacy/siteapp/static/s'+string
        if noface:
            fs = FileSystemStorage(location=location)
            fs.save(myfile.name, myfile)
            message="Successfully posted"
            imgob=imagesmodel()
            imgob.image=filenme
            imgob.uname=username
            imgob.save()
        elif(len(predicted_array)==1 and predicted_array[0]== username):
            fs = FileSystemStorage(location=location)
            fs.save(myfile.name, myfile)
            message="Successfully posted"
            imgob=imagesmodel()
            imgob.image=filenme
            imgob.uname=username
            imgob.save()
        else:
            for predicted_name in predicted_array:
                if predicted_name != username:
                    message="Looks like you are trying to add a photo "+predicted_name+" in . Sent request to the concern user.Please wait for the approval"
                    obj = posts() #gets new object
                    obj.fromuser= username
                    obj.touser = predicted_name
                    obj.message = username+" is trying to post a photo you might be in"
                    obj.permission = False
                    obj.image=temp_url
                    obj.location=subjects.index(username)
                    obj.typeof="req"
                    obj.testimageloc=uploaded_file_url
                    obj.save()




        
        context={
        'images':imgobj,
        'stringnum':string,
        'uploaded_file_url': uploaded_file_url,
        'message':message
        }
        return render(request, 'siteapp/feed.html',context)
    return render(request, 'siteapp/feed.html',context)


def notification(request):
    username = request.user.username
    queryset=posts.objects.filter(touser=username)
    if request.method == 'POST':
        idval=list(request.POST.keys())[1]
        temp=posts.objects.filter(id=idval)    
        tempobj=temp[0]
        if(tempobj.typeof=="req"):
            sendobj = posts()
            sendobj.fromuser= username
            sendobj.touser = tempobj.fromuser
            sendobj.message = "Status updated with "+username+"'s permission"
            sendobj.permission =False
            sendobj.location="/"
            sendobj.typeof="ack"
            sendobj.image=tempobj.image
            sendobj.testimageloc=tempobj.testimageloc
            sstring="C:/Users/rajgoku/Desktop/python pro/privacy/siteapp/static/test/"+tempobj.testimageloc
            print(sstring)
            imagefile=cv2.imread(sstring)
            open_cv_image = imagefile
            print(open_cv_image)
            path="C:/Users/rajgoku/Desktop/python pro/privacy/siteapp/static/s"+tempobj.location
            cv2.imwrite(os.path.join(path , tempobj.testimageloc), open_cv_image)
            sendobj.save()
            imgobj=imagesmodel()
            imgobj.image=tempobj.testimageloc
            imgobj.uname=tempobj.fromuser
            imgobj.save()
            tempobj.delete()
        else:
            tempobj.delete()





    context={
    'posts':queryset
    }
    return render(request, 'siteapp/notification.html',context)
    
# def feed(request):

#     image_names = os.listdir(path)
#     imagelist=[]
#     for image_name in image_names:
#             if image_name.startswith("."):
#                 continue;
#             image_name1="s"+string+"/"+image_name
#             imagelist.append(image_name1)
#     print(imagelist)
#     context={
#     'images':imagelist
#     }

#     return render(request, 'siteapp/feed.html',context)

siteapp/templates/siteapp/base.html




{% load static %}
<!DOCTYPE html>
<html lang="en">
<html>
<head>

    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

   
    <script defer src="https://use.fontawesome.com/releases/v5.0.8/js/all.js"></script>

    <title>Home</title>
  <meta charset="utf-8">
<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}" />
<script src="{% static 'js/bootstrap.min.js' %}" >
</script>
<script src="{% static 'js/jquery-3.3.1.js' %}" >
</script>


<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
<style>



</style>   

</head>
<body>




<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">Secured Social Website</a>
    </div>
    <ul class="nav navbar-nav navbar-right">
      <li class="active"><a href="#">Home</a></li>
      {% if user.is_authenticated %}
      <li><a href="#">Welcome {{ user.username }}</a></li>
       <li><a href="/feed">News feed</a></li>
       <li><a href="/profile">Profile</a></li>
        <li><a href="/notify">Notifications</a></li>
       <li><a href="/logout">Log out</a></li>
       {% else %}
         <li><a href="/login">Log in</a></li>
         <li><a href="/register">Register</a></li>


     {% endif %}
    
    </ul>
  </div>
</nav>



 {% block content %}
 {% endblock %}



 
</body>
</html>



siteapp/templates/siteapp/feed.html

{% extends 'siteapp/base.html' %}
 {% block content %}
<!-- 
<!DOCTYPE html>
<html lang="en">
<html>
<head>
    <title>Home</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
</head>
<body>
  <div class="container">

<nav class="navbar navbar-inverse bgnav">

    <div class="navbar-header">
      <a class="navbar-brand" href="/">Secured Social Website</a>
    </div>
<ul class="nav navbar-nav navbar-right ">
 <li><a href="/register">Register</a></li>
  {% if user.is_authenticated %}  
    <li><a href="#">welcome {{ user.username }}</a></li>
    <li><a href="/logout">Log out</a></li>
{% else %}
    <li><a href="/login">Please log in to continue</a></li>  
    
{% endif %}

  </ul>


</nav>
<br>
<br> -->








{% if user.is_authenticated %} 



{% static "" as baseurl %}

<br><br>

<div class="row">
  <div class="col-sm-4">
<div class="boxtype">
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
        <div class="">
            <h5>choose the image </h5></div>  
            <input type="file" class="form-control" name="myfile">
 <br>
      
        <button class="btn btn-primary " type="submit">Post </button>
    </div>
    </form>

</div>

<div class="war">

               {% if message %}
            <div class="well well-lg welll" style="background-color:#FFF">
    
                <p style="color: red;">{{message}}</p>
              </div>

      {% endif%} 

      {% if uploaded_file_url %}
        {% static "" as baseurl %}

<img src="{{baseurl}}test/{{uploaded_file_url}}" style="width:50%;height:10%;" style="width:50%" class="im"/>
{% endif %}

</div>



  
</div>
<style>
.vl {
    border-left: 6px solid #ee6e73;
    height: 620px;
}
</style>
<div class="col-sm-1">
<div class="vl"></div>
  </div>
<style>
.war{
  max-height: 3%;
    overflow-y: scroll;
        padding: 20px;
}
.over{
 /* background-color: lightblue;
    
    overflow: scroll;*/
  /*max-height: 40%;*/
  width: 700px;
    height: 1000px;
    overflow-y: scroll;
        padding: 20px;
}
.arrange{
  width: 65%;
}
</style>

<div class="col-sm-7">
  <h2>FEEDS</h2>
  <div class="over">

    <div class="arrange">

{% for image in images %}
      
        <div class="boxtype">
          <div class="card">
             <div class="card-content" >
            <h6 style="font-weight: bold;
    font-size: 14px;" >{{ user.username }} added a new photo</h6>
            </div>
            <div class="card-image">
               
              <img src="{{baseurl}}s{{stringnum}}/{{image.image}}" width="300px" height="50%"/> 
             
            </div>
            <br>
            <div class="card-content">
              <i class="fas fa-thumbs-up" style="font-size:20px"></i>Like &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        
          <i class="fas fa-comments" style="font-size:20px"></i>Comment&nbsp;&nbsp;
          <i class="fas fa-share" style="font-size:20px"></i>Share

            </div>
            <br>
            
                    <input type="text" placeholder="Comment on this post">
           
          </div>
        
     </div> 
{% endfor %}
</div>
</div>
<!-- 


  <img src="{{baseurl}}icons/{{user.username}}.jpg" width="17%" height="50%"/> -->
         <br>
         <br>


{% endif %}
</div>
</div>





<br>
<br><br><br><br><br><br><br><br>
   




</div>
<!-- </body>
</html> -->

{% endblock %}




{% for image in images %}
      <div class="row">
        <div class="col s12 m7">
          <div class="card">
            <div class="card-image">
              <img src="{{baseurl}}{{image}}" width="17%" height="50%"/> 
              <span class="card-title">Card Title</span>
            </div>
            <div class="card-content">
        
            </div>
            <div class="card-action">
              <a href="#">This is a link</a>
            </div>
          </div>
        </div>
      </div>
{% endfor %}

siteapp/templates/siteapp/home.html

{% extends 'siteapp/base.html' %}
 {% block content %}
<!-- 
<!DOCTYPE html>
<html lang="en">
<html>
<head>
    <title>Home</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
</head>
<body>
  <div class="container">

<nav class="navbar navbar-inverse bgnav">

    <div class="navbar-header">
      <a class="navbar-brand" href="#">Secured Social Website</a>
    </div>
<ul class="nav navbar-nav navbar-right ">
 <li><a href="/register">Register</a></li>
  {% if user.is_authenticated %}  
    <li><a href="#">welcome {{ user.username }}</a></li>
    <li><a href="/logout">Log out</a></li>
{% else %}
    <li><a href="/login">Please log in to continue</a></li>  
    
{% endif %}

  </ul>


</nav> -->
<br>
<br>




  <div class="row">
    <div class="col-sm-8 ">
      <p><img src=" {% static 'icons/I1.png'%}" />  &nbsp;&nbsp;&nbsp;&nbsp;Welcome to the Secured way of sharing data with Privacy Aware  Social Network </p>
       <p><img src=" {% static 'icons/I2.png'%}" />&nbsp;&nbsp;&nbsp;&nbsp;View photos and updates of your created community. </p>
       <p><img src=" {% static 'icons/I3.png'%}" />&nbsp;&nbsp;&nbsp;&nbsp;Find more and more details of what you're looking for. </p>

    </div>
    <div class="col-sm-4">
    <p><img src=" {% static 'icons/secure.jpg'%}" alt="secure image" height="20%" width="75%"/></p>
    </div>
    
  </div>







<!-- </body>
</html>


 -->
 
{% endblock %}

siteapp/templates/siteapp/index.html


<form action="{% url index %}" method="post" enctype="multipart/form-data">{% csrf_token %}
    <p>
        <input id="id_image" type="file" class="" name="image">
    </p>
    <input type="submit" value="Submit" />
</form>



siteapp/templates/siteapp/login.html

{% extends 'siteapp/base.html' %}
{% block content %}




<div class="boxtype">
    <form method="POST">
        {% csrf_token %}
        <div class="form-group">
        <p>
            <label>Username</label>
            <input type="text" class="form-control" name="username">
        </p>
        <p>
            <label>Password</label>
            <input type="password" class="form-control" name="password">
        </p>
        <button class="btn btn-primary" type="submit">Login</button>
    </div>
    </form>
</div>


{% endblock %}





siteapp/templates/siteapp/logout.html

{% extends 'siteapp/base.html' %}

{% block content %}

<h4></h4>>You have successfully logged out</h4>

{% endblock %}







siteapp/templates/siteapp/notification.html

{% extends 'siteapp/base.html' %}
<!-- 
<!DOCTYPE html>
<html lang="en">
<html>
<head>
    <title>Home</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
</head>
<body>
  <div class="container">

<nav class="navbar navbar-inverse bgnav">

    <div class="navbar-header">
      <a class="navbar-brand" href="/">Secured Social Website</a>
    </div>
<ul class="nav navbar-nav navbar-right ">
 <li><a href="/register">Register</a></li>
  {% if user.is_authenticated %}  
    <li><a href="#">welcome {{ user.username }}</a></li>
    <li><a href="/logout">Log out</a></li>
{% else %}
    <li><a href="/login">Please log in to continue</a></li>  
    
{% endif %}

  </ul>


</nav>
<br>
<br> -->





{% block content %}


{% if user.is_authenticated %} 



{% static "" as baseurl %}
 <h5>Your notifications:</h5>
 {%if posts %}
{% for post in posts %}
<div class="well">
<form method="POST">
   {% csrf_token %}
   <div class="row">
     <div class="col-sm-9">
       {{post.message}}
   </div>
    <div class="col-sm-1">
      {% if post.typeof == "req"%}<a href="{{baseurl}}test/{{post.testimageloc}}"     >view</a>{% endif  %}
    </div>
<div class="col-sm-2">
       {% if post.typeof == "req"%}
<input class="waves-effect waves-light btn" type="submit" name="{{post.id}}" value="accept">
{% endif  %}
<input class="waves-effect waves-light btn" type="submit" name="{{post.id}}" value="close"></div>
</div>
</form>
</div>  
{% endfor %}




<!-- 


  <img src="{{baseurl}}icons/{{user.username}}.jpg" width="17%" height="50%"/> -->
{% else %}
<h1><center>No Notifications</center></h1>
{% endif %}


{% endif %}







{% endblock %}

siteapp/templates/siteapp/post.html

{% extends 'siteapp/base.html' %}
 {% block content %}

<!-- <!DOCTYPE html>
<html lang="en">
<html>
<head>
    <title>Home</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
</head> 
<body>
 
 <div class="">
<nav class="navbar navbar-inverse bgnav">
 
    <div class="navbar-header">
      <a class="navbar-brand" href="/">Secured Social Website</a>
    </div>
    <ul class="nav navbar-nav navbar-right ">
         {% if user.is_authenticated %}  
    <li><a href="#">welcome {{ user.username }}</a></li>
    <li><a href="/logout">Log out</a></li>
    {% else %}
     <li><a href="/login">Please log in to continue</a></li>
{% endif %}
         <li><a href="/register">Register </a></li>

   </ul>

  
</nav>
 -->


<div class="boxtype">
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
        <div class="">
            <label>choose the image </label></div>  
            <input type="file" class="form-control" name="myfile">
   <br>
      
        <button class="btn btn-primary " type="submit">Post </button>
    </div>
    </form>

</div>

<br>

{% if message %}
<div class="well well-lg welll" style="background-color:#FFF">
    
    <p>{{message}}</p>
  </div>

{% endif%} 

{% if uploaded_file_url %}
{% static "" as baseurl %}

<img src="{{baseurl}}test/{{uploaded_file_url}}" style="width:500px;height:600px;" style="width:50%" class="im"/>
{% endif %}
</div>  

{% endblock %}






siteapp/templates/siteapp/profile.html

{% extends 'siteapp/base.html' %}
 {% block content %}
 {% load static %}

{% static "" as baseurl %}
 

  <div class="row">
    <div class="col-sm-5 ">
      <img src="{{baseurl}}icons/{{user.username}}.jpg" width="50%" height="50%"/>

    </div>
    <div class="col-sm-7">
   
Username : {{userobj.username}}<br>
First Name:{{userobj.first_name}}<br>
Last Name :{{userobj.last_name}}<br>
Email Id : {{userobj.email}}<br>
    </div>
    
  </div>

{% endblock %}

siteapp/templates/siteapp/signup.html
{% extends 'siteapp/base.html' %}
 {% block content %}


<div class="boxtype">

{% if user.is_authenticated %}
<div class="well"><p>
Please log out to create the new account
</p></div>
{% else %}
  {% load widget_tweaks %}  

    <form method="POST" >
         {% csrf_token %}
         <div class="form-group">
       
        <label >Username</label>
          {% render_field form.username class+="form-control " placeholder="Sgr" %}
          <label >First name</label>
          {% render_field form.first_name class+="form-control " placeholder="Gokul " %}
         <label >Last name </label>
         {% render_field form.last_name class+="form-control " placeholder="Raj" %}
          
    
         <label >Email id</label>
         {% render_field form.email class+="form-control " placeholder="abc@gmail.com" %}
            <label  >Password</label>
   {% render_field form.password class+="form-control " placeholder="***********" %}
    <label  >Proof</label>
   {% render_field form.image class+="form-control"%}





<br>
        <button class="btn btn-dprimary  " type="submit">Submit</button>
    </div>
    </form>
</div>

{% endif %}

{% endblock %}